---
title: "Branches for `Recca`"
author: "Matthew Kuperus Heun"
date: "`r Sys.Date()`"
output: html_document
---


## Purpose

This file (data-raw/branch_meta.Rmd) describes branches in this repository.
It will help us keep track of what we are doing and why.
The file lives in the `data-raw` directory, so it is not part of the package.

Information in this file supports my code development strategy,
which can be found in my
[github repository](https://github.com/MatthewHeun/DevelopmentStrategies).


## Branches

### master

The primary branch of the repository.

### develop

The branch into which new features are merged.

### Feature branches

Use this template to describe feature branches.

#### Branch name

* Purpose:
* Branched from:
* Next step:
* Author:
* Date:


#### irrev

* Purpose: Calculate losses and irreversibilities
* Branched from: develop
* Next step: Merge extend_to_exergy_with_losses_irrev() with extend_to_exergy()
* Author: MKH
* Date: 13 Jan 2026


#### merge_irrev

* Purpose: Move the functionality of extend_to_exergy_with_losses_irrev() into extend_to_exergy()
           with a boolean flag
* Branched from: irrev
* Next step:
* Author: MKH
* Date: 15 Jan 2026

